apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythin-app
  labels:
    app: servicepython
spec:
  replicas: 3  # Cambia según la cantidad de réplicas que necesites
  selector:
    matchLabels:
      app: servicepython
  template:
    metadata:
      labels:
        app: servicepython
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 30  # Ajustado a 30 segundos, dependiendo de las necesidades de tu aplicación
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: server
        image: "anarkigotic/mi-aplicacion-python:v0"
        ports:
        - containerPort: 5000
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
