apiVersion: apps/v1
kind: Deployment
metadata:
  name: juan-node
  labels:
    app: juanservice
spec:
  selector:
    matchLabels:
      app: juanservice
  template:
    metadata:
      labels:
        app: juanservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "anarkigotic/mi-aplicacion-juan:v5"
        ports:
        - containerPort: 7070