apiVersion: v1
kind: Service
metadata:
  name: ejemplo-service
spec:
  selector:
    app: mi-aplicacion  # Selector para encontrar los pods del servicio
  ports:
    - protocol: TCP
      port: 5000  # Puerto expuesto por el servicio
      targetPort: 5000  # Puerto al que redirige el servicio en los pods
  type: LoadBalancer  # Tipo de servicio, en este caso LoadBalancer
