apiVersion: v1
kind: Service
metadata:
  name: juan-node-service
spec:
  selector:
    app: juanservice  # Selecciona los pods con la etiqueta "app: juanservice"
  ports:
    - protocol: TCP
      port: 5000       # Puerto del servicio
      targetPort: 5000  # Puerto en el que se ejecuta tu aplicación dentro de los pods
  type: LoadBalancer  # Tipo de servicio, se define como LoadBalancer para que Kubernetes cree un balanceador de carga externo
