apiVersion: v1
kind: Service
metadata:
  name: mi-aplicacion-flask
spec:
  selector:
    app: mi-aplicacion-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
